# Generated by Django 3.2.16 on 2024-07-12 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_follow_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата подписки'),
            preserve_default=False,
        ),
    ]
